// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR2OVDStSdElAa0w1bocutfrdwyvZRdxk',
    appId: '1:977823336947:web:0a306ed40d104190e5ea86',
    messagingSenderId: '977823336947',
    projectId: 'bullyng-5857f',
    authDomain: 'bullyng-5857f.firebaseapp.com',
    storageBucket: 'bullyng-5857f.firebasestorage.app',
    measurementId: 'G-L8X3V63J2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYymQN3tIeVQuzfBEg00ldr-AOTyUbd84',
    appId: '1:977823336947:android:16344971ac011b94e5ea86',
    messagingSenderId: '977823336947',
    projectId: 'bullyng-5857f',
    storageBucket: 'bullyng-5857f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIG3nuRHt5cbpOx2rf0Egjw5bCBFZduY',
    appId: '1:977823336947:ios:7a994bcb51a36f15e5ea86',
    messagingSenderId: '977823336947',
    projectId: 'bullyng-5857f',
    storageBucket: 'bullyng-5857f.firebasestorage.app',
    iosBundleId: 'com.example.appBullying',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIIG3nuRHt5cbpOx2rf0Egjw5bCBFZduY',
    appId: '1:977823336947:ios:7a994bcb51a36f15e5ea86',
    messagingSenderId: '977823336947',
    projectId: 'bullyng-5857f',
    storageBucket: 'bullyng-5857f.firebasestorage.app',
    iosBundleId: 'com.example.appBullying',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR2OVDStSdElAa0w1bocutfrdwyvZRdxk',
    appId: '1:977823336947:web:8121e53cdf0819dee5ea86',
    messagingSenderId: '977823336947',
    projectId: 'bullyng-5857f',
    authDomain: 'bullyng-5857f.firebaseapp.com',
    storageBucket: 'bullyng-5857f.firebasestorage.app',
    measurementId: 'G-MECXQT0WGQ',
  );

}